package mnj.mfg.model.views;

import mnj.mfg.model.entities.DeatilsEOImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 09 21:28:46 PKT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DeatilsEOViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        DetailId {
            public Object get(DeatilsEOViewRowImpl obj) {
                return obj.getDetailId();
            }

            public void put(DeatilsEOViewRowImpl obj, Object value) {
                obj.setDetailId((Number)value);
            }
        }
        ,
        LineId {
            public Object get(DeatilsEOViewRowImpl obj) {
                return obj.getLineId();
            }

            public void put(DeatilsEOViewRowImpl obj, Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        MinorOperation {
            public Object get(DeatilsEOViewRowImpl obj) {
                return obj.getMinorOperation();
            }

            public void put(DeatilsEOViewRowImpl obj, Object value) {
                obj.setMinorOperation((String)value);
            }
        }
        ,
        MajorOpId {
            public Object get(DeatilsEOViewRowImpl obj) {
                return obj.getMajorOpId();
            }

            public void put(DeatilsEOViewRowImpl obj, Object value) {
                obj.setMajorOpId((Number)value);
            }
        }
        ,
        Smv {
            public Object get(DeatilsEOViewRowImpl obj) {
                return obj.getSmv();
            }

            public void put(DeatilsEOViewRowImpl obj, Object value) {
                obj.setSmv((Number)value);
            }
        }
        ,
        CreatedBy {
            public Object get(DeatilsEOViewRowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(DeatilsEOViewRowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        LastUdatedBy {
            public Object get(DeatilsEOViewRowImpl obj) {
                return obj.getLastUdatedBy();
            }

            public void put(DeatilsEOViewRowImpl obj, Object value) {
                obj.setLastUdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(DeatilsEOViewRowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(DeatilsEOViewRowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        EffectiveStartDate {
            public Object get(DeatilsEOViewRowImpl obj) {
                return obj.getEffectiveStartDate();
            }

            public void put(DeatilsEOViewRowImpl obj, Object value) {
                obj.setEffectiveStartDate((Date)value);
            }
        }
        ,
        EffectiveEndDate {
            public Object get(DeatilsEOViewRowImpl obj) {
                return obj.getEffectiveEndDate();
            }

            public void put(DeatilsEOViewRowImpl obj, Object value) {
                obj.setEffectiveEndDate((Date)value);
            }
        }
        ,
        OperationCode {
            public Object get(DeatilsEOViewRowImpl obj) {
                return obj.getOperationCode();
            }

            public void put(DeatilsEOViewRowImpl obj, Object value) {
                obj.setOperationCode((String)value);
            }
        }
        ,
        MachineType {
            public Object get(DeatilsEOViewRowImpl obj) {
                return obj.getMachineType();
            }

            public void put(DeatilsEOViewRowImpl obj, Object value) {
                obj.setMachineType((String)value);
            }
        }
        ,
        MajorOperation {
            public Object get(DeatilsEOViewRowImpl obj) {
                return obj.getMajorOperation();
            }

            public void put(DeatilsEOViewRowImpl obj, Object value) {
                obj.setMajorOperation((String)value);
            }
        }
        ,
        bomoperations1 {
            public Object get(DeatilsEOViewRowImpl obj) {
                return obj.getbomoperations1();
            }

            public void put(DeatilsEOViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(DeatilsEOViewRowImpl object);

        public abstract void put(DeatilsEOViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DETAILID = AttributesEnum.DetailId.index();
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int MINOROPERATION = AttributesEnum.MinorOperation.index();
    public static final int MAJOROPID = AttributesEnum.MajorOpId.index();
    public static final int SMV = AttributesEnum.Smv.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUDATEDBY = AttributesEnum.LastUdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int EFFECTIVESTARTDATE = AttributesEnum.EffectiveStartDate.index();
    public static final int EFFECTIVEENDDATE = AttributesEnum.EffectiveEndDate.index();
    public static final int OPERATIONCODE = AttributesEnum.OperationCode.index();
    public static final int MACHINETYPE = AttributesEnum.MachineType.index();
    public static final int MAJOROPERATION = AttributesEnum.MajorOperation.index();
    public static final int BOMOPERATIONS1 = AttributesEnum.bomoperations1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DeatilsEOViewRowImpl() {
    }

    /**
     * Gets DeatilsEO entity object.
     * @return the DeatilsEO
     */
    public DeatilsEOImpl getDeatilsEO() {
        return (DeatilsEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for DETAIL_ID using the alias name DetailId.
     * @return the DETAIL_ID
     */
    public Number getDetailId() {
        return (Number) getAttributeInternal(DETAILID);
    }

    /**
     * Sets <code>value</code> as attribute value for DETAIL_ID using the alias name DetailId.
     * @param value value to set the DETAIL_ID
     */
    public void setDetailId(Number value) {
        setAttributeInternal(DETAILID, value);
    }

    /**
     * Gets the attribute value for LINE_ID using the alias name LineId.
     * @return the LINE_ID
     */
    public Number getLineId() {
        return (Number) getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_ID using the alias name LineId.
     * @param value value to set the LINE_ID
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for MINOR_OPERATION using the alias name MinorOperation.
     * @return the MINOR_OPERATION
     */
    public String getMinorOperation() {
        return (String) getAttributeInternal(MINOROPERATION);
    }

    /**
     * Sets <code>value</code> as attribute value for MINOR_OPERATION using the alias name MinorOperation.
     * @param value value to set the MINOR_OPERATION
     */
    public void setMinorOperation(String value) {
        setAttributeInternal(MINOROPERATION, value);
    }

    /**
     * Gets the attribute value for MAJOR_OP_ID using the alias name MajorOpId.
     * @return the MAJOR_OP_ID
     */
    public Number getMajorOpId() {
        return (Number) getAttributeInternal(MAJOROPID);
    }

    /**
     * Sets <code>value</code> as attribute value for MAJOR_OP_ID using the alias name MajorOpId.
     * @param value value to set the MAJOR_OP_ID
     */
    public void setMajorOpId(Number value) {
        setAttributeInternal(MAJOROPID, value);
    }

    /**
     * Gets the attribute value for SMV using the alias name Smv.
     * @return the SMV
     */
    public Number getSmv() {
        return (Number) getAttributeInternal(SMV);
    }

    /**
     * Sets <code>value</code> as attribute value for SMV using the alias name Smv.
     * @param value value to set the SMV
     */
    public void setSmv(Number value) {
        setAttributeInternal(SMV, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UDATED_BY using the alias name LastUdatedBy.
     * @return the LAST_UDATED_BY
     */
    public Number getLastUdatedBy() {
        return (Number) getAttributeInternal(LASTUDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UDATED_BY using the alias name LastUdatedBy.
     * @param value value to set the LAST_UDATED_BY
     */
    public void setLastUdatedBy(Number value) {
        setAttributeInternal(LASTUDATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for EFFECTIVE_START_DATE using the alias name EffectiveStartDate.
     * @return the EFFECTIVE_START_DATE
     */
    public Date getEffectiveStartDate() {
        return (Date) getAttributeInternal(EFFECTIVESTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EFFECTIVE_START_DATE using the alias name EffectiveStartDate.
     * @param value value to set the EFFECTIVE_START_DATE
     */
    public void setEffectiveStartDate(Date value) {
        setAttributeInternal(EFFECTIVESTARTDATE, value);
    }

    /**
     * Gets the attribute value for EFFECTIVE_END_DATE using the alias name EffectiveEndDate.
     * @return the EFFECTIVE_END_DATE
     */
    public Date getEffectiveEndDate() {
        return (Date) getAttributeInternal(EFFECTIVEENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EFFECTIVE_END_DATE using the alias name EffectiveEndDate.
     * @param value value to set the EFFECTIVE_END_DATE
     */
    public void setEffectiveEndDate(Date value) {
        setAttributeInternal(EFFECTIVEENDDATE, value);
    }


    /**
     * Gets the attribute value for MAJOR_OPERATION using the alias name MajorOperation.
     * @return the MAJOR_OPERATION
     */
    public String getMajorOperation() {
        return (String) getAttributeInternal(MAJOROPERATION);
    }

    /**
     * Sets <code>value</code> as attribute value for MAJOR_OPERATION using the alias name MajorOperation.
     * @param value value to set the MAJOR_OPERATION
     */
    public void setMajorOperation(String value) {
        setAttributeInternal(MAJOROPERATION, value);
    }

    /**
     * Gets the attribute value for OPERATION_CODE using the alias name OperationCode.
     * @return the OPERATION_CODE
     */
    public String getOperationCode() {
        return (String) getAttributeInternal(OPERATIONCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for OPERATION_CODE using the alias name OperationCode.
     * @param value value to set the OPERATION_CODE
     */
    public void setOperationCode(String value) {
        setAttributeInternal(OPERATIONCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute MachineType.
     * @return the MachineType
     */
    public String getMachineType() {
        return (String) getAttributeInternal(MACHINETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute MachineType.
     * @param value value to set the  MachineType
     */
    public void setMachineType(String value) {
        setAttributeInternal(MACHINETYPE, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> bomoperations1.
     */
    public RowSet getbomoperations1() {
        return (RowSet)getAttributeInternal(BOMOPERATIONS1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
