package mnj.mfg.model.lov.views;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 26 13:58:04 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class buyerRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        KnownAs {
            public Object get(buyerRowImpl obj) {
                return obj.getKnownAs();
            }

            public void put(buyerRowImpl obj, Object value) {
                obj.setKnownAs((String)value);
            }
        }
        ,
        CustAccountId {
            public Object get(buyerRowImpl obj) {
                return obj.getCustAccountId();
            }

            public void put(buyerRowImpl obj, Object value) {
                obj.setCustAccountId((Number)value);
            }
        }
        ,
        CustomerName {
            public Object get(buyerRowImpl obj) {
                return obj.getCustomerName();
            }

            public void put(buyerRowImpl obj, Object value) {
                obj.setCustomerName((String)value);
            }
        }
        ,
        CustomerId {
            public Object get(buyerRowImpl obj) {
                return obj.getCustomerId();
            }

            public void put(buyerRowImpl obj, Object value) {
                obj.setCustomerId((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(buyerRowImpl object);

        public abstract void put(buyerRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int KNOWNAS = AttributesEnum.KnownAs.index();
    public static final int CUSTACCOUNTID = AttributesEnum.CustAccountId.index();
    public static final int CUSTOMERNAME = AttributesEnum.CustomerName.index();
    public static final int CUSTOMERID = AttributesEnum.CustomerId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public buyerRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute KnownAs.
     * @return the KnownAs
     */
    public String getKnownAs() {
        return (String) getAttributeInternal(KNOWNAS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute KnownAs.
     * @param value value to set the  KnownAs
     */
    public void setKnownAs(String value) {
        setAttributeInternal(KNOWNAS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustAccountId.
     * @return the CustAccountId
     */
    public Number getCustAccountId() {
        return (Number) getAttributeInternal(CUSTACCOUNTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustAccountId.
     * @param value value to set the  CustAccountId
     */
    public void setCustAccountId(Number value) {
        setAttributeInternal(CUSTACCOUNTID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerName.
     * @return the CustomerName
     */
    public String getCustomerName() {
        return (String) getAttributeInternal(CUSTOMERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerName.
     * @param value value to set the  CustomerName
     */
    public void setCustomerName(String value) {
        setAttributeInternal(CUSTOMERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CustomerId.
     * @return the CustomerId
     */
    public Number getCustomerId() {
        return (Number) getAttributeInternal(CUSTOMERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CustomerId.
     * @param value value to set the  CustomerId
     */
    public void setCustomerId(Number value) {
        setAttributeInternal(CUSTOMERID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
