package mnj.mfg.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 26 14:33:45 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ColorImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ColorImpl() {
    }


    /**
     * Returns the bind variable value for style_name.
     * @return bind variable value for style_name
     */
    public String getstyle_name() {
        return (String)getNamedWhereClauseParam("style_name");
    }

    /**
     * Sets <code>value</code> for bind variable style_name.
     * @param value value to bind as style_name
     */
    public void setstyle_name(String value) {
        setNamedWhereClauseParam("style_name", value);
    }
}
