package mnj.mfg.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 05 12:29:38 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class operatingUnitsVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public operatingUnitsVOImpl() {
    }
}
