package mnj.mfg.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 26 14:17:35 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StyleImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public StyleImpl() {
    }


    /**
     * Returns the bind variable value for p_customerID.
     * @return bind variable value for p_customerID
     */
    public String getp_customerID() {
        return (String)getNamedWhereClauseParam("p_customerID");
    }

    /**
     * Sets <code>value</code> for bind variable p_customerID.
     * @param value value to bind as p_customerID
     */
    public void setp_customerID(String value) {
        setNamedWhereClauseParam("p_customerID", value);
    }

    /**
     * Returns the bind variable value for p_Org_Id.
     * @return bind variable value for p_Org_Id
     */
    public String getp_Org_Id() {
        return (String)getNamedWhereClauseParam("p_Org_Id");
    }

    /**
     * Sets <code>value</code> for bind variable p_Org_Id.
     * @param value value to bind as p_Org_Id
     */
    public void setp_Org_Id(String value) {
        setNamedWhereClauseParam("p_Org_Id", value);
    }
}
