package mnj.mfg.model.lov.views;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 26 14:17:35 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StyleRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        StyleName {
            public Object get(StyleRowImpl obj) {
                return obj.getStyleName();
            }

            public void put(StyleRowImpl obj, Object value) {
                obj.setStyleName((String)value);
            }
        }
        ,
        Season {
            public Object get(StyleRowImpl obj) {
                return obj.getSeason();
            }

            public void put(StyleRowImpl obj, Object value) {
                obj.setSeason((String)value);
            }
        }
        ,
        OrganizationId {
            public Object get(StyleRowImpl obj) {
                return obj.getOrganizationId();
            }

            public void put(StyleRowImpl obj, Object value) {
                obj.setOrganizationId((Number)value);
            }
        }
        ,
        CurrentStyle {
            public Object get(StyleRowImpl obj) {
                return obj.getCurrentStyle();
            }

            public void put(StyleRowImpl obj, Object value) {
                obj.setCurrentStyle((String)value);
            }
        }
        ,
        CurrentSeason {
            public Object get(StyleRowImpl obj) {
                return obj.getCurrentSeason();
            }

            public void put(StyleRowImpl obj, Object value) {
                obj.setCurrentSeason((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(StyleRowImpl object);

        public abstract void put(StyleRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int STYLENAME = AttributesEnum.StyleName.index();
    public static final int SEASON = AttributesEnum.Season.index();
    public static final int ORGANIZATIONID = AttributesEnum.OrganizationId.index();
    public static final int CURRENTSTYLE = AttributesEnum.CurrentStyle.index();
    public static final int CURRENTSEASON = AttributesEnum.CurrentSeason.index();

    /**
     * This is the default constructor (do not remove).
     */
    public StyleRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute StyleName.
     * @return the StyleName
     */
    public String getStyleName() {
        return (String) getAttributeInternal(STYLENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StyleName.
     * @param value value to set the  StyleName
     */
    public void setStyleName(String value) {
        setAttributeInternal(STYLENAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Season.
     * @return the Season
     */
    public String getSeason() {
        return (String) getAttributeInternal(SEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Season.
     * @param value value to set the  Season
     */
    public void setSeason(String value) {
        setAttributeInternal(SEASON, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrganizationId.
     * @return the OrganizationId
     */
    public Number getOrganizationId() {
        return (Number) getAttributeInternal(ORGANIZATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrganizationId.
     * @param value value to set the  OrganizationId
     */
    public void setOrganizationId(Number value) {
        setAttributeInternal(ORGANIZATIONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentStyle.
     * @return the CurrentStyle
     */
    public String getCurrentStyle() {
        return (String) getAttributeInternal(CURRENTSTYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentStyle.
     * @param value value to set the  CurrentStyle
     */
    public void setCurrentStyle(String value) {
        setAttributeInternal(CURRENTSTYLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentSeason.
     * @return the CurrentSeason
     */
    public String getCurrentSeason() {
        return (String) getAttributeInternal(CURRENTSEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentSeason.
     * @param value value to set the  CurrentSeason
     */
    public void setCurrentSeason(String value) {
        setAttributeInternal(CURRENTSEASON, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
